using UnityEngine;
using Steamworks;
using System.Collections.Generic;

public class LobbyUI : MonoBehaviour
{
    private CSteamID currentLobbyID;
    private bool isHost = false;
    
    void Update()
    {
        if (Time.frameCount % 60 == 0 && currentLobbyID != CSteamID.Nil)
        {
            RefreshLobbyInfo();
        }
    }
    
    void RefreshLobbyInfo()
    {
        if (currentLobbyID == CSteamID.Nil)
        {
            return;
        }
        
        string info = "";
        
        // Lobi adÄ±
        string lobbyName = SteamMatchmaking.GetLobbyData(currentLobbyID, "name");
        info += $"<b>LOBÄ°: {lobbyName}</b>\n\n";
        
        // Host mu Client mÄ±?
        if (isHost)
        {
            info += "<color=yellow>ðŸ‘‘ SÄ°Z HOST'SUNUZ</color>\n\n";
        }
        else
        {
            info += "<color=cyan>ðŸŽ® SÄ°Z OYUNCUSUNUZ</color>\n\n";
        }
        
        // Oyuncu listesi
        int memberCount = SteamMatchmaking.GetNumLobbyMembers(currentLobbyID);
        info += $"<b>OYUNCULAR ({memberCount}/4):</b>\n";
        
        for (int i = 0; i < memberCount; i++)
        {
            CSteamID memberID = SteamMatchmaking.GetLobbyMemberByIndex(currentLobbyID, i);
            string memberName = SteamFriends.GetFriendPersonaName(memberID);
            
            // Host iÅŸareti
            string hostID = SteamMatchmaking.GetLobbyData(currentLobbyID, "host");
            if (memberID.ToString() == hostID)
            {
                info += $"  ðŸ‘‘ {memberName} <color=yellow>(Host)</color>\n";
            }
            else
            {
                info += $"  ðŸŽ® {memberName}\n";
            }
        }
        
        // P2P baÄŸlantÄ± durumu
        info += "\n<b>P2P BAÄžLANTILAR:</b>\n";
        int connectedCount = NetworkManager.Instance.GetConnectedPlayerCount();
        info += $"  BaÄŸlÄ± oyuncu: {connectedCount}\n";
        
        List<CSteamID> connectedPlayers = NetworkManager.Instance.GetConnectedPlayers();
        foreach (CSteamID playerID in connectedPlayers)
        {
            string playerName = SteamFriends.GetFriendPersonaName(playerID);
            info += $"  âœ… {playerName}\n";
        }
    }

}